#!/usr/bin/env bash
# Install RoboCasa conda env "robocasa" — idempotent, non-interactive.
#
# Why a separate env: RoboCasa setup.py hard-pins mujoco==3.3.1 / numpy==2.2.5,
# which collides with everything else in the main `mujoco` env (dm_control,
# mjlab, mujoco_playground need mujoco>=3.7/3.8). Keep its mess in its own box.
#
# Layout choices (kept here, not in the notebook, so callers stay 1-line):
#   - submodule path:        dependencies/robocasa
#   - conda env name:        robocasa
#   - dataset path:          $ROBOCASA_DATA_PATH (default $HOME/.cache/robocasa)
#     persisted via <env>/etc/conda/activate.d/robocasa.sh
#
# Run from any CWD inside the repo; we cd to git root.

set -euo pipefail

ENV_NAME="${ROBOCASA_ENV_NAME:-robocasa}"
SUBMOD="dependencies/robocasa"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# ---------- 0. shared dataset dir ---------------------------------------------
export ROBOCASA_DATA_PATH="${ROBOCASA_DATA_PATH:-$HOME/.cache/robocasa}"
mkdir -p "$ROBOCASA_DATA_PATH/datasets"
echo ">>> ROBOCASA_DATA_PATH=$ROBOCASA_DATA_PATH"

# ---------- 1. submodule ------------------------------------------------------
if [[ ! -f "$SUBMOD/setup.py" ]]; then
  echo ">>> init submodule $SUBMOD ..."
  git submodule update --init "$SUBMOD"
fi

# ---------- 2. locate conda ---------------------------------------------------
CONDA_BIN="${CONDA_EXE:-$(command -v conda || true)}"
if [[ -z "$CONDA_BIN" ]]; then
  echo "ERROR: conda not found in PATH or \$CONDA_EXE" >&2
  exit 1
fi
CONDA_BASE="$("$CONDA_BIN" info --base)"
# shellcheck disable=SC1091
source "$CONDA_BASE/etc/profile.d/conda.sh"

# ---------- 3. create env if missing -----------------------------------------
ENV_DIR="$CONDA_BASE/envs/$ENV_NAME"
if conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
  echo ">>> conda env [$ENV_NAME] exists, skip create"
else
  echo ">>> creating conda env [$ENV_NAME] python=3.11 ..."
  conda create -c conda-forge -n "$ENV_NAME" python=3.11 -y
fi

conda activate "$ENV_NAME"

# ---------- 4. install robosuite (master branch, NOT PyPI) --------------------
# RoboCasa requires the latest robosuite master, not the PyPI release.
if ! python -c "import robosuite" 2>/dev/null; then
  echo ">>> installing robosuite from master ..."
  pip install --no-cache-dir "git+https://github.com/ARISE-Initiative/robosuite.git@master"
fi

# robosuite_models: ships extra robot URDFs (Tiago etc.). Optional but cheap.
if ! python -c "import robosuite_models" 2>/dev/null; then
  echo ">>> installing robosuite_models ..."
  pip install --no-cache-dir robosuite_models || echo "WARN: robosuite_models install failed"
fi

# ---------- 5. install robocasa (editable from submodule) --------------------
if ! python -c "import robocasa" 2>/dev/null; then
  echo ">>> pip install -e $SUBMOD ..."
  pip install -e "$SUBMOD"
fi

# ---------- 6. set up macros_private + DATASET_BASE_PATH ---------------------
# robocasa.__init__ prints a "WARNING: mimicgen..." line to stdout, so we tag
# the path with a sentinel and grep it out.
ROBOCASA_PKG_DIR="$(python -c 'import robocasa, os; print("##PKG##"+os.path.dirname(robocasa.__file__))' 2>/dev/null | sed -n 's/^##PKG##//p')"
if [[ -z "$ROBOCASA_PKG_DIR" || ! -d "$ROBOCASA_PKG_DIR" ]]; then
  echo "ERROR: failed to locate robocasa package dir (got: $ROBOCASA_PKG_DIR)" >&2
  exit 1
fi
MACROS_PRIVATE="$ROBOCASA_PKG_DIR/macros_private.py"
cat > "$MACROS_PRIVATE" <<EOF
# auto-generated by scripts/install_robocasa_env.sh
import os
DATASET_BASE_PATH = os.environ.get("ROBOCASA_DATA_PATH", os.path.expanduser("~/.cache/robocasa")) + "/datasets"
EOF
echo ">>> wrote $MACROS_PRIVATE"

# ---------- 7. download kitchen assets (~10GB, idempotent) -------------------
# download_kitchen_assets interactively prompts; pipe "y" to accept.
# Each registry entry checks check_folder_exists itself, so re-runs are cheap.
echo ">>> downloading kitchen assets to $ROBOCASA_PKG_DIR/models/assets ..."
yes y | python -m robocasa.scripts.download_kitchen_assets --type all || {
  echo "WARN: download_kitchen_assets exited non-zero; some assets may be missing"
}

# ---------- 8. persist ROBOCASA_DATA_PATH in activate hook -------------------
ACT_DIR="$ENV_DIR/etc/conda/activate.d"
mkdir -p "$ACT_DIR"
cat > "$ACT_DIR/robocasa.sh" <<EOF
# auto-generated by scripts/install_robocasa_env.sh
export ROBOCASA_DATA_PATH="\${ROBOCASA_DATA_PATH:-\$HOME/.cache/robocasa}"
# Avoid Python 3.11 quickened-opcode poisoning of .pyc when robocasa registers
# ~700 envs through gymnasium (symptom: SystemError: unknown opcode 182).
export PYTHONDONTWRITEBYTECODE=1
EOF
echo ">>> wrote activate hook: $ACT_DIR/robocasa.sh"

# Also clear any existing stale bytecode that might have been written before the fix.
echo ">>> clearing stale .pyc caches ..."
find "$REPO_ROOT/$SUBMOD" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
SITE_PACKAGES="$ENV_DIR/lib/python3.11/site-packages"
for pkg in gymnasium gym robosuite robosuite_models; do
  find "$SITE_PACKAGES/$pkg" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
done

echo ""
echo "=============================================="
echo "RoboCasa env ready. Activate with:"
echo "  conda activate $ENV_NAME"
echo "Quick test:"
echo "  python -c 'import robocasa; print(robocasa.__version__)'"
echo "=============================================="
