#!/usr/bin/env bash
# Install GR00T eval conda env "robocasa_gr00t" — idempotent.
#
# Why a separate env: GR00T pins torch==2.5.1 / numpy==1.26.4 / TF 2.15;
# robocasa pins numpy==2.2.5. They can't share an env. The eval pipeline
# is two-process: this env hosts the inference server, the existing
# `robocasa` env hosts the sim client.
#
# Layout:
#   - submodule path:        dependencies/Isaac-GR00T (robocasa-benchmark fork)
#   - conda env name:        robocasa_gr00t
#   - checkpoint path:       $ROBOCASA_DATA_PATH/checkpoints/gr00t_n1-5/...

set -euo pipefail

ENV_NAME="${ROBOCASA_GR00T_ENV_NAME:-robocasa_gr00t}"
SUBMOD="dependencies/Isaac-GR00T"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

export ROBOCASA_DATA_PATH="${ROBOCASA_DATA_PATH:-$HOME/.cache/robocasa}"

# ---------- 1. submodule ------------------------------------------------------
if [[ ! -f "$SUBMOD/pyproject.toml" ]]; then
  echo ">>> init submodule $SUBMOD ..."
  GIT_LFS_SKIP_SMUDGE=1 git submodule update --init "$SUBMOD"
fi

# ---------- 2. locate conda ---------------------------------------------------
CONDA_BIN="${CONDA_EXE:-$(command -v conda || true)}"
if [[ -z "$CONDA_BIN" ]]; then
  echo "ERROR: conda not found" >&2
  exit 1
fi
CONDA_BASE="$("$CONDA_BIN" info --base)"
# shellcheck disable=SC1091
source "$CONDA_BASE/etc/profile.d/conda.sh"

# ---------- 3. create env if missing -----------------------------------------
ENV_DIR="$CONDA_BASE/envs/$ENV_NAME"
if conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
  echo ">>> conda env [$ENV_NAME] exists, skip create"
else
  echo ">>> creating conda env [$ENV_NAME] python=3.10 ..."
  conda create -c conda-forge -n "$ENV_NAME" python=3.10 -y
fi
conda activate "$ENV_NAME"

# ---------- 4. install gr00t + base deps -------------------------------------
# Follows Isaac-GR00T/Dockerfile recipe.
if ! python -c "import gr00t" 2>/dev/null; then
  echo ">>> pip install -e $SUBMOD[base] ..."
  pip install --upgrade pip setuptools
  pip install -e "$SUBMOD[base]"
fi

# Pin torch/numpy after [base] to match Dockerfile (avoids subtle ABI breakage).
echo ">>> pinning torch==2.5.1 numpy==1.26.4 ..."
pip install --force-reinstall \
  torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 numpy==1.26.4 \
  --extra-index-url https://download.pytorch.org/whl/cu124

# transformer-engine sometimes ships with pytorch images; drop it (Dockerfile does).
pip uninstall -y transformer-engine 2>/dev/null || true

# ---------- 5. flash-attn (required by Qwen2 backbone) -----------------------
# The eagle2_5_vl backbone asserts `_attn_implementation == "flash_attention_2"`,
# so this is non-optional. Prebuilt wheel matched to torch 2.5 / cuda 12.4.
if ! python -c "import flash_attn" 2>/dev/null; then
  echo ">>> installing flash-attn 2.7.1.post4 ..."
  pip install flash-attn==2.7.1.post4 --no-build-isolation || {
    echo "WARN: flash-attn wheel not found; trying source build (slow, needs CUDA toolkit)"
    pip install flash-attn==2.7.1.post4 --no-build-isolation --no-binary flash-attn
  }
fi

# zmq for the inference server protocol
pip install --quiet pyzmq

# ---------- 6. activate hook --------------------------------------------------
ACT_DIR="$ENV_DIR/etc/conda/activate.d"
mkdir -p "$ACT_DIR"
cat > "$ACT_DIR/robocasa_gr00t.sh" <<EOF
# auto-generated by scripts/install_gr00t_env.sh
export ROBOCASA_DATA_PATH="\${ROBOCASA_DATA_PATH:-\$HOME/.cache/robocasa}"
EOF

# Install pyzmq into robocasa env too (client needs it).
echo ">>> installing pyzmq into robocasa env ..."
conda deactivate
conda activate robocasa
pip install --quiet pyzmq

echo ""
echo "=============================================="
echo "GR00T eval env ready."
echo "  server env: $ENV_NAME (gr00t + flash-attn)"
echo "  client env: robocasa (sim + zmq)"
echo "Quick test:"
echo "  python scripts/robocasa_eval_gr00t.py --env-name CloseFridge --n-episodes 2"
echo "=============================================="
